# Generated by Django 5.2.4 on 2025-08-02 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='F_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='L_name',
        ),
    ]
