# Generated by Django 5.2.4 on 2025-08-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='account/default_user.jpg', null=True, upload_to='account/'),
        ),
    ]
